name: PR Checks

on:
    pull_request:
        branches: ["master"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set Up Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 20
          cache: 'npm'
      - name: Installing node modules
        run: npm ci
      - name: Run Unit Test
        run: npm run test
